export const LOADING_START = 'LOADING_START'
export const LOADING_FINISH = 'LOADING_FINISH'
export const LOADING_FAILED = 'LOADING_FAILED'
export const DATA_LOADED = 'DATA_LOADED'
export const RATE_LOADED = 'RATE_LOADED'
export const RATE_FAILED = 'RATE_FAILED'

